let btn_color = ["red", "blue", "green", "yellow"];

// generate the pattern using the random number
let game_pattern = [];

// gating the pattern from the user 
let click_pattern = [];

// for the heading 
let start = false;
let level = 0;

// after every game level start with 0
$(document).keydown(function () {
  if (!start) {
    $("#level-title").text("Level " + level);
    next_seq();
    start = true;
  }
});

// clicking effect on every button
$(".btn").click(function () {
  let user_chosen_color = $(this).attr("id");
  click_pattern.push(user_chosen_color);
  // console.log(click_pattern);

  playsong(user_chosen_color);
  animation(user_chosen_color);

  check_ans(click_pattern.length - 1);
});

// for checking the both pattern, generated by random number and from the use input  
function check_ans(current_level) {
  if (game_pattern[current_level] === click_pattern[current_level]) {
    if (game_pattern.length === click_pattern.length) {
      setTimeout(function () {
        next_seq();
      }, 1000);
    }
  } 
  else {
    // after effect when game is over
    playsong("wrong");

    $("body").addClass("game-over");
    $("#level-title").text("Game over.press any key to restart");

    setTimeout(function () {
      $("body").removeClass("game-over");
    }, 200);

    restart();
  }
}

function next_seq() {
  click_pattern = []; //after every level user input restore to the null

  level++;
  $("#level-title").text("Level " + level);

  // generated random number
  let rnum = Math.floor(Math.random() * 4);
  let chosen_color = btn_color[rnum];
  game_pattern.push(chosen_color);

  // for the animation of changing the color
  $("#" + chosen_color)
    .fadeIn(100)
    .fadeOut(100)
    .fadeIn(100);
 
  playsong(chosen_color);
}

// for the button song
function playsong(name) {
  let song = new Audio("sounds/" + name + ".mp3");
  song.play();
}

// animation of clicking effect
function animation(cur_color) {
  $("#" + cur_color).addClass("pressed");
  setTimeout(() => {
    $("#" + cur_color).removeClass("pressed");
  }, 100);
}

// when game is over start from the begine.
function restart() {
  game_pattern = [];
  level = 0;
  start = false;
}
